version: '2'
services:
  backend_db:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=backend
      - MYSQL_ROOT_PASSWORD=root
  backend:
    image: drytools/maven
    working_dir: /home/docker/backend
    volumes:
      - ../backend/:/home/docker/backend
    ports:
      - "8080:8080"
    links:
      - backend_db
    command: mvn spring-boot:run

     